/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Calculator;

/**
 *
 * @author Programming
 */
public class MyCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MyCalculator
     */
    public MyCalculator() {
        initComponents();
        jPOn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jDisplay = new javax.swing.JTextField();
        jPOn = new javax.swing.JToggleButton();
        jPOff = new javax.swing.JToggleButton();
        jBtn4 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jDotBtn = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jResultBtn = new javax.swing.JButton();
        jMulBtn = new javax.swing.JButton();
        jSubBtn = new javax.swing.JButton();
        jDivBtn = new javax.swing.JButton();
        jAddBtn = new javax.swing.JButton();
        jResetBtn = new javax.swing.JButton();
        jDelBtn = new javax.swing.JButton();
        jModBtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDisplay.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jDisplay.setToolTipText("Oloko");
        jDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayActionPerformed(evt);
            }
        });

        jPOn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPOn.setText("ON");
        jPOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPOnActionPerformed(evt);
            }
        });

        jPOff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPOff.setText("OFF");
        jPOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPOffActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jDotBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDotBtn.setText(".");
        jDotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDotBtnActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jResultBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jResultBtn.setText("=");
        jResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResultBtnActionPerformed(evt);
            }
        });

        jMulBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMulBtn.setText("*");
        jMulBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMulBtnActionPerformed(evt);
            }
        });

        jSubBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSubBtn.setText("-");
        jSubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubBtnActionPerformed(evt);
            }
        });

        jDivBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDivBtn.setText("/");
        jDivBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivBtnActionPerformed(evt);
            }
        });

        jAddBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jAddBtn.setText("+");
        jAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBtnActionPerformed(evt);
            }
        });

        jResetBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jResetBtn.setText("C");
        jResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetBtnActionPerformed(evt);
            }
        });

        jDelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDelBtn.setText("<");
        jDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelBtnActionPerformed(evt);
            }
        });

        jModBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jModBtn.setText("%");
        jModBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDisplay)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPOn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPOff, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jResetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn9, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jBtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jResultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMulBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jSubBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDivBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jModBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jModBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPOn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPOff, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63))
                                .addComponent(jSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jMulBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jDivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jDesktopPane3.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDesktopPane2.setLayer(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane3)
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMulBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMulBtnActionPerformed
        if(!(jDisplay.getText().isEmpty())){
            jDisplay.setText(jDisplay.getText() + "*");
        }
    }//GEN-LAST:event_jMulBtnActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn6.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn6.getText());
        }
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn2.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn2.getText());
        }
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn5.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn5.getText());
        }
    }//GEN-LAST:event_jBtn5ActionPerformed

    @SuppressWarnings("StringEquality")
    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn1.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn1.getText());
        }
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jPOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPOffActionPerformed
       jResultBtn.setEnabled(false);
       jDotBtn.setEnabled(false);
       jBtn0.setEnabled(false);
       jBtn1.setEnabled(false);
       jBtn2.setEnabled(false);
       jBtn3.setEnabled(false);
       jBtn4.setEnabled(false);
       jBtn5.setEnabled(false);
       jBtn6.setEnabled(false);
       jBtn7.setEnabled(false);
       jBtn8.setEnabled(false);
       jBtn9.setEnabled(false);
       jAddBtn.setEnabled(false);
       jSubBtn.setEnabled(false);
       jMulBtn.setEnabled(false);
       jDivBtn.setEnabled(false);
       jDelBtn.setEnabled(false);
       jResetBtn.setEnabled(false);
       jModBtn.setEnabled(false);
       
       jPOff.setEnabled(false);
       jPOn.setEnabled(true);
       jDisplay.setText("Goodbye! Oloko");
       jDisplay.setEnabled(false);
    }//GEN-LAST:event_jPOffActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn3.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn3.getText());
        }
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
       if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn4.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn4.getText());
        }
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn7.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn7.getText());
        }
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn8.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn8.getText());
        }
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn9.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn9.getText());
        }
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        if(jDisplay.getText().isBlank()){
            jDisplay.setText(jBtn0.getText());
        }
        else{
            jDisplay.setText(jDisplay.getText()+ jBtn0.getText());
        }
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBtnActionPerformed
        if(!(jDisplay.getText().isEmpty())){
            jDisplay.setText(jDisplay.getText() + "+");
        }   
    }//GEN-LAST:event_jAddBtnActionPerformed

    private void jResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResultBtnActionPerformed
        
        if(jDisplay.getText().contains("+")){
            Double operand1=Double.parseDouble(jDisplay.getText().substring(0, jDisplay.getText().indexOf("+")));
            Double operand2=Double.parseDouble(jDisplay.getText().substring((jDisplay.getText().lastIndexOf("+")+1), jDisplay.getText().length()));
            Double result= operand1 + operand2;
            
            jDisplay.setText(result.toString());
        }else if(jDisplay.getText().contains("-")){
            Double operand1=Double.parseDouble(jDisplay.getText().substring(0, jDisplay.getText().indexOf("-")));
            Double operand2=Double.parseDouble(jDisplay.getText().substring((jDisplay.getText().lastIndexOf("-")+1), jDisplay.getText().length()));
            Double result= operand1 - operand2;
            
            jDisplay.setText(result.toString());
        }else if(jDisplay.getText().contains("*")){
            Double operand1=Double.parseDouble(jDisplay.getText().substring(0, jDisplay.getText().indexOf("*")));
            Double operand2=Double.parseDouble(jDisplay.getText().substring((jDisplay.getText().lastIndexOf("*")+1), jDisplay.getText().length()));
            Double result= operand1 * operand2;
            
            jDisplay.setText(result.toString());
        }else if(jDisplay.getText().contains("/")){
            Double operand1=Double.parseDouble(jDisplay.getText().substring(0, jDisplay.getText().indexOf("/")));
            Double operand2=Double.parseDouble(jDisplay.getText().substring((jDisplay.getText().lastIndexOf("/")+1), jDisplay.getText().length()));
            Double result= operand1 / operand2;
            
            jDisplay.setText(result.toString());
        }else if(jDisplay.getText().contains("%")){
            Double operand1=Double.parseDouble(jDisplay.getText().substring(0, jDisplay.getText().indexOf("%")));
            Double operand2=Double.parseDouble(jDisplay.getText().substring((jDisplay.getText().lastIndexOf("%")+1), jDisplay.getText().length()));
            Double result= operand1 % operand2;
            
            jDisplay.setText(result.toString());
        }
    }//GEN-LAST:event_jResultBtnActionPerformed

    private void jSubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubBtnActionPerformed
        if(!(jDisplay.getText().isEmpty())){
            jDisplay.setText(jDisplay.getText() + "-");
        }
    }//GEN-LAST:event_jSubBtnActionPerformed

    private void jDivBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivBtnActionPerformed
        if(!(jDisplay.getText().isEmpty())){
            jDisplay.setText(jDisplay.getText() + "/");
        }
    }//GEN-LAST:event_jDivBtnActionPerformed

    private void jDotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDotBtnActionPerformed
       if(!jDisplay.getText().isEmpty() && !jDisplay.getText().contains(".")){
           jDisplay.setText(jDisplay.getText() + jDotBtn.getText());
       }
    }//GEN-LAST:event_jDotBtnActionPerformed

    private void jResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetBtnActionPerformed
        jDisplay.setText("");
    }//GEN-LAST:event_jResetBtnActionPerformed

    private void jDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelBtnActionPerformed
        if(!(jDisplay.getText().isEmpty())){
            jDisplay.setText(jDisplay.getText().substring(0, jDisplay.getText().length()-1));
        }
    }//GEN-LAST:event_jDelBtnActionPerformed

    private void jModBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModBtnActionPerformed
        if(!(jDisplay.getText().isEmpty())){
            jDisplay.setText(jDisplay.getText() + "%");
        }   
    }//GEN-LAST:event_jModBtnActionPerformed

    private void jPOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPOnActionPerformed
       jResultBtn.setEnabled(true);
       jDotBtn.setEnabled(true);
       jBtn0.setEnabled(true);
       jBtn1.setEnabled(true);
       jBtn2.setEnabled(true);
       jBtn3.setEnabled(true);
       jBtn4.setEnabled(true);
       jBtn5.setEnabled(true);
       jBtn6.setEnabled(true);
       jBtn7.setEnabled(true);
       jBtn8.setEnabled(true);
       jBtn9.setEnabled(true);
       jAddBtn.setEnabled(true);
       jSubBtn.setEnabled(true);
       jMulBtn.setEnabled(true);
       jDivBtn.setEnabled(true);
       jDelBtn.setEnabled(true);
       jResetBtn.setEnabled(true);
       jModBtn.setEnabled(true);
       
       jPOn.setEnabled(false);
       jPOff.setEnabled(true);
       jDisplay.setText("");
       jDisplay.setEnabled(true);
    }//GEN-LAST:event_jPOnActionPerformed

    private void jDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayActionPerformed
    }//GEN-LAST:event_jDisplayActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAddBtn;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jDelBtn;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JTextField jDisplay;
    private javax.swing.JButton jDivBtn;
    private javax.swing.JButton jDotBtn;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jModBtn;
    private javax.swing.JButton jMulBtn;
    private javax.swing.JToggleButton jPOff;
    private javax.swing.JToggleButton jPOn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jResetBtn;
    private javax.swing.JButton jResultBtn;
    private javax.swing.JButton jSubBtn;
    // End of variables declaration//GEN-END:variables
}
